name: 'Cache'
inputs:
  local_path:
    description: 'A directory to store and save the cache'
    required: true
  cache_path:
    description: 'A local directory to store and save the cache'
    required: true
runs:
  using: 'node12'
  main: main.js
  post: post.js
  post-if: 'success()'
branding:
  icon: 'archive'
  color: 'gray-dark'
